### PR TITLE
[LUCIANA] Hello World

### PR DESCRIPTION
**Pull request by lucianaDilizio**
hello world

### CODE REVIEW

**Comment by andresmoschini** [comment]
What do you think about using your github or makingsense name in place of _Luciana_?

**Comment by andresmoschini** [comment]
Oh, you merged it before, hehe. Poor little kitten.

image

**Comment by lucianaDilizio** [comment]
Hahaha! @andresmoschini I just wanted to put what I did in the repo. It's not an important commit but everybody can feel free to comment. I didn't have any intention to fix mistakes with this first commit.

**Comment by lucianaDilizio** [comment]
> What do you think about using your github or makingsense name in place of Luciana?
Do you mean about the commits nomenclature @andresmoschini?

**Comment by andresmoschini** [comment]
Right, for example using `lucianaDilizio` or `lgarcia` in place of `Luciana`. In that way we could avoid ambiguities

**Comment by lucianaDilizio** [comment]
OK! So I will change the folder name too and the next branch I will name it `lgarcia`.

**Pull request merged**
